/**
 * Pet Store API
 * A simple API to manage a pet store
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("PetsApi", () => {
  let instance: api.PetsApi
  beforeEach(function() {
    instance = new api.PetsApi(config)
  });

  test("listPets", () => {
    return expect(instance.listPets({})).resolves.toBe(null)
  })
})

